### ISSUE TITLE
Why is moq and NUnit here?

### ISSUE THREAD

**Issue by jpek42** [jrjackso/CCNetSlackPublisher#5]
Curious why you're including the Moq and NUnit stuff in lib, instead of just letting these come in as Nuget packages?

**Comment by jrjackso** [comment]
They are nuget packages and are managed by nuget, but I've checked them in. (I've seen a number of blog posts, etc. recommending to check them in like http://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful/ and http://www.jayway.com/2015/03/27/check-in-your-nuget-packages/ ). That said, I'm not too committed to any approach; we just do this where I work so it felt more familiar.

**Comment by jrjackso** [comment]
I actually think you might be running into something with a newer version of nuget. The nuget.config changed schema a little. The config currently checked in has:

`<settings>
    <repositoryPath>lib</repositoryPath>
</settings>`

If you are using a newer version of nuget, I believe this has to be changed to:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="lib" />
  </config>
</configuration>`

Let me know if that's related to your question, and if so we can update the nuget.config to support the newer version.

**Comment by jpek42** [comment]
Personally, I don't think the "check in your packages" advice makes any sense at all. It also works at cross-purposes with Git, which really doesn't want to be encumbered by the package stuff.

You may be right about the nuget.config. I didn't really pay close attention. For me, it created a "packages" directory, which I assumed was being used, until I noticed the lib folder reference in the project.

I think the "right" way to handle this would be to allow nuget to add the reference into the packages directory, and trash the files in lib.

**Comment by jrjackso** [comment]
@jpek42 : Moved everything over to package restore and deleted checked in nuget deps. Dependencies updated to new versions and built with VS 2015 now.  That should wrap up this issue hopefully (closed). Let me know if you run into anything!
