### ISSUE TITLE
CCnet.exe crashes on startup after adding slackPublisher to config file

### ISSUE THREAD

**Issue by gakera** [jrjackso/CCNetSlackPublisher#7]
I built the project and copied the dll to the CruiseControl.NET\server folder folder as instructed and added the slackPublisher line to the config file with the unique webhook from slack. When I start ccnet.exe now it just crashes immediately, no output. If I debug the program I see that a System.Configuration.ConfigurationException is thrown with the inner exception "Unrecognized configuration section publishers. (C:\Program Files (x86)\CruiseControl.NET\server\ccnet.exe.Config line 167)"

Is there anything else I need to do, where should the `<publishers>` section go into the config file? I added it at the bottom, between `</runtime>` and `</configuration>`

**Comment by jrjackso** [comment]
The `<publishers>` should go within a `<project>` tag, at the bottom. E.g.
`<project name=xxx>
...
<triggers>...</triggers>
...
<tasks>...</tasks>
...
<publishers>
...
<slackPublisher webhookUrl=.../>
</publishers>
</project>`

Let me know if that helps.

**Comment by jrjackso** [comment]
There is a good example of a project block here: http://cruisecontrolnet.org/projects/ccnet/wiki/Project_Configuration_Block

**Comment by gakera** [comment]
Yea I was just a dumbass and was adding this to the ccnet.exe.Config file rather than the ccnet.Config file. They're so similarly named that I didn't realize (and the instructions don't assume stupidity).
